version: '3.9'

services:
  # mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # node api service
  api:
    build: .
    ports:
      - 4000:8000
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo_db:27017/projectory
      JWT_SECRET: aldjfkldjalkjflkglooejlj4972957jfdlajfjdfjjfadfa
      JWT_EXPIRES_IN: 15d
      NODE_MAILER_USERNAME: 
      CLIENT_ID: 
      CLIENT_SECRET: 
      CLIENT_REDIRECT_URI: https://developers.google.com/oauthplayground
      REFRESH_TOKEN: 
      FRONT_END_URL: http://localhost:3000
      CLOUD_NAME: 
      CLOUD_API_KEY: 
      CLOUD_SECRET: 
      STRIPE_KEY: 
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
